### PR TITLE
[Gtk] Implement the new FontChooserDialog

### PR DESCRIPTION
**Pull request by cra0zy**
Implements the new FontChooserDialog: https://developer.gnome.org/gtk3/stable/GtkFontChooserDialog.html

PS. I also fixed up some code formatting in ColorChooser.

### CODE REVIEW

**Comment by cwensley** [comment]
\o/

**Comment by cra0zy** [comment]
\o?

**Comment by cwensley** [comment]
Head and arms..  aka YAY!  Maybe it's just me that uses that.. ¯\_(ツ)_/¯

**Comment by cra0zy** [comment]
> Head and arms.. aka YAY! Maybe it's just me that uses that.. ¯\_(ツ)_/¯

Don't worry, I got the meaning, that's why I responded with the same thing, tho I did write "\o?" instead of "\o/" because I accidentally pressed shift and changed it really fast.

**Comment by cwensley** [comment]
ah, I thought you were asking what I meant with the ?  (;

**Pull request merged**
