### PR TITLE
In progress: Drag 'n Drop for the masses.

### PR DESCRIPTION
**Pull request by cwensley**

### CODE REVIEW

**Comment by SlowLogicBoy** [comment]
I need to try this like right now.

**Comment by cwensley** [comment]
@SlowLogicBoy Sorry, you probably won't get very far as it's a work in progress. It doesn't really work on anything other than WPF at the moment, and it has issues to boot.

**Comment by cwensley** [comment]
I'm currently starting to implement this for macOS, which will by far be the hardest part of this as its drag 'n drop infrastructure is quite different from windows or gtk.

**Comment by SlowLogicBoy** [comment]
Well, I'm using Wpf platform mainly, I just want to see how mock up looks like :) and I bet this will change with time, just too excited about this :)

**Comment by cwensley** [comment]
Ok, I can guarantee there's going to be bugs with this one.  I could use some help testing the different platforms and features. Anyone have some free cycles for testing?

**Comment by TomQv** [comment]
Cool ! Long awaited, Thanks.
Will try Wpf and Mac the next days.
Tom

**Pull request merged**
