### PR TITLE
Implement Gtk file filters

### PR DESCRIPTION
**Pull request by ermshiperete**
[Review on Reviewable](https://reviewable.io/reviews/picoe/eto/399)

### CODE REVIEW

**Comment by ermshiperete** [comment]
I can't see a reason for the failed build other than that the artifact upload failed.

**Comment by cwensley** [comment]
Great, thanks for the PR!  It looks great.  since this is your first contribution, just need you to agree to license this and any future contributions under the same license as Eto (BSD-3).  Thanks!

**Comment by ermshiperete** [comment]
No problem. I agree to license this and any future contributions under the same license as Eto.

**Comment by cwensley** [comment]
Great!  Thanks again for the contribution.

**Pull request merged**
