### PR TITLE
Fix  #2252: [GTK] Non-disposed (Leaking) Cairo.Surface when assigning Application.BadgeLabel

### LINKED ISSUE #2252: [GTK] Non-disposed (Leaking) Cairo.Surface when assigning Application.BadgeLabel
## Expected Behavior
I can assign the `Application.BadgeLabel` property with just a string.

## Actual Behavior
Assigning to the field causes Cairo to produce a warning:
```
Cairo.Surface is leaking, programmer is missing a call to Dispose
Allocated from:
   at System.Environment.get_StackTrace()
   at Cairo.CairoDebug.OnAllocated(IntPtr obj)
   at Cairo.Surface..ctor(IntPtr handle, Boolean owner)
   at Cairo.ImageSurface..ctor(Format format, Int32 width, Int32 height)
   at Eto.GtkSharp.Drawing.GraphicsHandler.CreateFromImage(Bitmap image)
   at Eto.Drawing.Graphics..ctor(Bitmap image)
   at Eto.GtkSharp.Forms.ApplicationHandler.set_BadgeLabel(String value)
   at Eto.Forms.Application.set_BadgeLabel(String value)
   at ************************************************ (My code)
```

## Steps to Reproduce the Problem

  1. Be using the GTK Platform
  2. Create a new `Application` object and assign the `.BadgeLabel` property
  3. ```application = new Application(platform)
			{
					Name = "[Name]",
					ID   = "Main Application",
					UIThreadCheckMode = UIThreadCheckMode.Error,
					BadgeLabel = "[Badge]"
			};
  4. See the above error be printed to the console (stacktrace only appears if `MONO_CAIRO_DEBUG_DISPOSE=1` env variable is set)

## Code that Demonstrates the Problem

Full project on [Github](https://github.com/Ararem/RayTracer/tree/899700eadaf312a4110e632a5daa791cb7d7eae6) - you want `RayTracer.Display.Dev` which I'm currently rewriting
```
application = new Application(platform)
{
		Name = "[Name]",
		ID   = "Main Application",
		UIThreadCheckMode = UIThreadCheckMode.Error,
		BadgeLabel = "[Badge]"
};
```

## Specifications

  - Version: ETO.Forms 2.6.1
  - Platform(s): GTK Confirmer, others untested
  - Operating System(s): POP!_OS 22.04 LTS

## Notes
I think the issue is caused by `Eto.GtkSharp.Forms.ApplicationHandler.BadgeLabel.set` ([source](https://github.com/picoe/Eto/blob/develop/src/Eto.Gtk/Forms/ApplicationHandler.cs#L91=)). The issue is that while the `Graphics` object is disposed, the inner `Bitmap` (and probably the inner-inner `BitmapHandler`) don't get disposed. I propose the following to fix the issue:
Replace
```csharp
using (var graphics = new Graphics(new Bitmap(new BitmapHandler(bmp))))
{
	graphics.Clear();
	DrawBadgeLabel(graphics, new Size(bmp.Width, bmp.Height), badgeLabel);
}
```
With
```csharp
using BitmapHandler bitmapHandler = new(bmp);
using Bitmap bitmap = new (bitmapHandler);
using Graphic graphics = new (bitmap);
graphics.Clear();
DrawBadgeLabel(graphics, new Size(bmp.Width, bmp.Height), badgeLabel);
//Automatically disposed because of using statement
```

### PR DESCRIPTION
**Pull request by ghost**
Add using statements to correctly dispose all IDisposable objects when setting `BadgeLabel` for GTK `Application.IHandler`.

See #2252 

Signed-off-by: ararem <48875125+Ararem@users.noreply.github.com>

### CODE REVIEW

**Comment by cwensley** [comment]
Thanks for this, though I can't quite merge this in as it appears to have commits that are for another issue.  Could you clean that up so it only has the changes for this issue?  You may need to create a different branch and create another PR.

**Comment by ghost** [comment]
Ugh my apologies I find github branches and merging really tricky. Can I just upload the modified file here instead?

Only relevant commit is https://github.com/picoe/Eto/pull/2301/commits/2677a9f5b51c9477d9e148eb84a55ba849a8fa42

Replace lines 90-96
```csharp
var bmp = new Gdk.Pixbuf(Gdk.Colorspace.Rgb, true, 8, 32, 32);
using (var graphics = new Graphics(new Bitmap(new BitmapHandler(bmp))))
{
	graphics.Clear();
	DrawBadgeLabel(graphics, new Size(bmp.Width, bmp.Height), badgeLabel);
}
statusIcon.Pixbuf = bmp;
```

changes to:

```csharp
var pixbuf = new Gdk.Pixbuf(Gdk.Colorspace.Rgb, true, 8, 32, 32);
using(var bmpHandler = new BitmapHandler(pixbuf))
{
	using(var bitmap     = new Bitmap(bmpHandler))
	{
		using (var graphics = new Graphics(bitmap))
		{
			graphics.Clear();
			DrawBadgeLabel(graphics, new Size(pixbuf.Width, pixbuf.Height), badgeLabel);
		}
	}
}

statusIcon.Pixbuf = pixbuf;
```


Replace lines 109-113:
```csharp
graphics.DrawEllipse(new Pen(Colors.White, 2), rect);
var font = new Font(SystemFont.Bold, 10);
var labelSize = graphics.MeasureString(font, badgeLabel);
var labelPosition = ((PointF)(rect.Size - labelSize) / 2) + rect.Location;
graphics.DrawText(font, Colors.White, labelPosition, badgeLabel);
```

changes to:

```csharp
using (var pen = new Pen(Colors.White, 2))
{
	graphics.DrawEllipse(pen, rect);
}
using (var font = new Font(SystemFont.Bold, 10))
{
	var labelSize     = graphics.MeasureString(font, badgeLabel);
	var labelPosition = ((PointF)(rect.Size - labelSize) / 2) + rect.Location;
	graphics.DrawText(font, Colors.White, labelPosition, badgeLabel);
}
```

**Comment by Miepee** [comment]
@Ararem would you mind if I open a new PR that only has the needed commit?

**Comment by ghost** [comment]
> @Ararem would you mind if I open a new PR that only has the needed commit?

Yeah sure do whatever you want! I would do it myself but I'm very bogged down at the moment.

**Comment by cwensley** [comment]
Closing as this was fixed in the other PR. Thanks again @Ararem and @Miepee

**Pull request closed without merging**
