### PR TITLE
[WIP] Eto.NativeGTK

### PR DESCRIPTION
**Pull request by cra0zy**
**NOT READY FOR MERGE**

@cwensley I thought I might open a WIP PR so you can see what I'm working on. I'll create a separate PR for merging once all the base controls are ported over.

### CODE REVIEW

**Comment by rconde01** [comment]
The point of this is to get rid of the Gtk# dependency?

**Comment by cra0zy** [comment]
> The point of this is to get rid of the Gtk# dependency?

Yes.

**Comment by cwensley** [comment]
@cra0zy oh that's great, thanks for doing that!  It's awesome to see progress on this, as it will certainly be the preferred linux platform once done. (;  

I'm liking how it looks so far!  I guess the idea is once everything is migrated to remove the use of Gtk.Widget?

**Comment by cra0zy** [comment]
> I guess the idea is once everything is migrated to remove the use of Gtk.Widget?

Yess.

**Comment by cra0zy** [comment]
@cwensley I think I've stabilized the base structure that I'll be going for, so if you can, please go over the classes added to the NativeGtk project file and tell me if you want something changed, since it's probably gonna be way harder to change it once more stuff is added.

**Comment by cra0zy** [comment]
@cwensley  I'm just gonna assume that you're fine with how I structured the base for wrapper calling and continue adding stuff.

**Comment by cwensley** [comment]
@cra0zy hey sorry it took a bit but I just finished reviewing it.  I like it, it seems clean and will be just as easy to maintain (possibly easier) as the current Gtk platform.

How do you intend on dealing with different dll/dylib/so names on each platform?  Similar to the current Gtk stuff?

**Comment by cra0zy** [comment]
> How do you intend on dealing with different dll/dylib/so names on each platform? Similar to the current Gtk stuff?

If there are no improvements in .Net Core on that part by the time I'm done, I'll modify the generator script to generate 3 sets of functions. I hope that won't be necessary.

**Comment by cwensley** [comment]
> If there are no improvements in .Net Core on that part by the time I'm done, I'll modify the generator script to generate 3 sets of functions. I hope that won't be necessary.

Awesome.  I hope not either but I wouldn't hold my breath (;

**Pull request closed without merging**
