### PR TITLE
Fix for ToolItemCollection items being added in wrong order

### PR DESCRIPTION
**Pull request by JosefNemec**
Happened to me only when toolbar items were being added as Command classes.

### CODE REVIEW

**Comment by cwensley** [comment]
Thanks for the pull!  Do you have a repro for the problem you're running into?  This pull request appears like it would break the ability to set the order of the item using the ToolItem.Order property.

**Comment by cwensley** [comment]
Thanks for the pull!  I've committed a fix for this while still keeping the ability to create order groups.  Hopefully this will fix it for you as well.  Let me know if it doesn't. (;

Cheers!
Curtis.

**Comment by JosefNemec** [comment]
Great, sorry that I didn't fixed it my self, I haven't had much time lately.

**Comment by cwensley** [comment]
No problem at all!  Thanks for pointing out the issue. (;

**Pull request closed without merging**
