### PR TITLE
[GTK] Fix GetCallingAssembly

### PR DESCRIPTION
**Pull request by cra0zy**

### CODE REVIEW

**Comment by cra0zy** [comment]
@cwensley PS. The error with this is between .NET Core and .NET Framework / mono, they do have a different amount of calls in the stacktrace.

**Comment by cwensley** [comment]
Hm, a few thoughts.. 

1. Perhaps we should be comparing the Assembly directly, not just the name?  
2. Also, it might make sense to find Eto, then continue until the assembly that is not Eto.. unless that is where the extra frame(s) are located..

**Comment by cra0zy** [comment]
> Perhaps we should be comparing the Assembly directly, not just the name?

I thought that as well at the start, but then I realized that we really only care about those few names, and they are gonna be unique anyways.

> Also, it might make sense to find Eto, then continue until the assembly that is not Eto.. unless that is where the extra frame(s) are located..

Can't do that because the frames go something like: Eto.Gtk -> mscore/System -> Eto -> Calling Assembly

**Comment by cwensley** [comment]
> but then I realized that we really only care about those few names, and they are gonna be unique anyways.

True, though I was thinking more for performance, loading a ton of bitmaps/icons for example.

> Eto.Gtk -> mscore/System -> Eto -> Calling Assembly

That's what I mean..  Find Eto, then find the next assembly after it.  No need to test for Eto.Gtk, mscorlib, System. etc.  Not a big deal, though would make it work if used in any platform assembly.

**Comment by cra0zy** [comment]
@cwensley Done.

**Pull request merged**
