### PR TITLE
Added Visual SEO Studio to the list of Apps using Eto

### PR DESCRIPTION
**Pull request by msasso69**
I'm quite new to Pull Requests and I'm not sure that I have included only the change to README.md (as intended) or also other crap, hope not

### CODE REVIEW

**Comment by cwensley** [comment]
Hey @msasso69, awesome, thanks for adding it to the list!  You have a pretty cool project. 

It looks like you did a merge into your own branch from picoe/develop, which changes its history (hence is why it is showing 4 commits above, instead of one).

What you would typically do for a PR is to create a new branch from upstream (picoe/develop), add your changes, then submit your PR from that branch.  It keeps things clean, and you can do multiple PR's with different changes.

Luckily, GitHub has options to "fix" the history by rebasing your branch on the base branch before committing which should resolve the issue.  You can also do the same on your end to "clean" your branch.

**Comment by msasso69** [comment]
Thanks for the hint! I'll rebase my repo.
Just one question: how come my link is not "linked" to the text "Visual SEO Studio"?
image
 It's because of the space between brackets? "] ("
image

**Comment by cwensley** [comment]
Yeah that’s probably it. Sorry I didn’t catch that.

**Comment by msasso69** [comment]
Should I make a new pull request?

**Comment by cwensley** [comment]
No worries. Making single-file edits is easy right within GitHub though so I don't mind fixing it.

**Pull request merged**
