### PR TITLE
Add secure passwordbox

### PR DESCRIPTION
**Pull request by mennodeij**
This PR adds a more secure implementation of the PasswordBox using a SecureString as backing store. 
I have tested this with WPF and Gtk3 - I don't have access to other platforms.

### CODE REVIEW

**Comment by mennodeij** [comment]
Hmm... Maybe I'm missing something here, but the AppVeyor build did _not_ build my additions. It checked out https://github.com/picoe/Eto.git and built that.

**Comment by cwensley** [comment]
Hey @mennodeij, thanks for the PR!

Unfortunately, it's usefulness on mono is fairly limited, as [SecureString isn't actually secure](https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Security/SecureString.cs#L253).  

That being said, it might be worth investigating whether the existing `PasswordBox` can be updated to add a `SecureString` property instead - on WPF at least it has a `SecurePassword` property so this can be directly accessed and will indeed be fully secure. 

What do you think?

**Comment by mennodeij** [comment]
Would that mean that on WPF the password is only stored securely?

**Comment by cwensley** [comment]
@mennodeij right, it wouldn't be secure on any platform other than WPF or WinForms.  

Even then, the security of it all is suspect as eventually you translate it to a normal string to actually use it.  Also, on [msdn](https://msdn.microsoft.com/en-us/library/system.security.securestring(v=vs.110).aspx) it states: 
> On the Windows operating system, the contents of a SecureString instance's internal character array is encrypted. However, whether because of missing APIs or key management issues, encryption is not available on all platforms. Because of this, SecureString is available on Desktop (Windows only), and not on .NET Core.

So, it's not really useful as it isn't cross platform at all.

I'll close this now but if you feel like it should still be in Eto, let me know!

**Pull request closed without merging**
