### PR TITLE
Refined ProgressCell.

### PR DESCRIPTION
**Pull request by BaseCrosser**
Min value is forced to -1.
Max value is forced to 100.
Also I added that when the value is -1 it doesn't draw the ProgressCell.

### CODE REVIEW

**Comment by cwensley** [comment]
Hm, would it make sense to make it a nullable float?  if it is null, then it wouldn't show anything, and the percentage value is 0 - 1.  This will allow it to be more precise as well, and not limited to 100 steps.

**Comment by BaseCrosser** [comment]
I'll look into it tommorow. Don't have much time today for it.

**Comment by cwensley** [comment]
Awesome, no problem at all (;

**Comment by BaseCrosser** [comment]
It won't work with the native progress bar on GTK# the way you suggested.
It can't handle a NULL value. What do you suggest? Keep it with Int values or draw it ourselfs on GTK# (sorta like DrawableCell)?

**Comment by cwensley** [comment]
Could the float be translated to an int value or perhaps a float.NaN if it is null (for GTK specifically)?

**Comment by BaseCrosser** [comment]
I got it to work on Gtk now. Thanks for the tip.
Mac also needed the float.NaN way.
I'll upload it in a minute or 5.

Quick question, is this right?
https://github.com/picoe/Eto/blob/develop/Source/Eto.Mac/Forms/FormHandler.cs#L70
Doesn't it need to be ```if (Control.IsVisible)```
I am asking this because OnShown doesn't fire on Mac nad when searching for the problem I came across this.

**Comment by BaseCrosser** [comment]
I accidentaly deleted all my progress but I'm done now.
I think this is good to go now.

**Comment by cwensley** [comment]
Great work again!  Thanks!

**Pull request merged**
