### PR TITLE
[Mac] use proper text alignment on arm64

### LINKED ISSUE #2250: Text alignment is incorrect on arm64 macos
On arm64 macos, the enum use ios values, so center and right alignment is interchanged.
 
``` objective-c
#define TARGET_ABI_USES_IOS_VALUES  (!TARGET_CPU_X86_64 || (TARGET_OS_IPHONE && !TARGET_OS_MACCATALYST))
typedef NS_ENUM(NSInteger, NSTextAlignment) {
    NSTextAlignmentLeft      = 0,    // Visually left aligned
#if TARGET_ABI_USES_IOS_VALUES
    NSTextAlignmentCenter    = 1,    // Visually centered
    NSTextAlignmentRight     = 2,    // Visually right aligned
#else /* !TARGET_ABI_USES_IOS_VALUES */
    NSTextAlignmentRight     = 1,    // Visually right aligned
    NSTextAlignmentCenter    = 2,    // Visually centered
#endif
    NSTextAlignmentJustified = 3,    // Fully-justified. The last line in a paragraph is natural-aligned.
    NSTextAlignmentNatural   = 4     // Indicates the default alignment for script
} API_AVAILABLE(macos(10.0), ios(6.0), watchos(2.0), tvos(9.0));
 ```
 
  - Version: 2.7.0
  - Platform(s): Mac64
  - Operating System(s):  MacOS 12.0.1

### PR DESCRIPTION
**Pull request by Miepee**
TextAlignment Right and Center are switched up on Arm64 Macos. So this PR fixes this by giving the switched up version in the ToEto/ToNS functions if the current running system is Arm.

Fixes #2250 (don't have a mac device currently, so didn't actually test).

### CODE REVIEW

**Comment by cwensley** [comment]
Thanks for the fix @Miepee!

I'm not sure if the net7.0-macos workload already deals with this so that needs to be looked into first.  If it does, the fix should probably go into MonoMac instead of in Eto.

**Comment by Miepee** [comment]
Does the net7.0 workload use xamarin? if yes, it seems to have been merged about a year ago: https://github.com/xamarin/xamarin-macios/issues/12111

**Comment by cwensley** [comment]
Yes they are the same. So we should do a similar fix for the MonoMac submodule instead.

**Comment by Miepee** [comment]
Gotcha, will mark as ready to review then when I moved the fix to monomac.

**Comment by Miepee** [comment]
Guess i was too slow, sorry for that

**Comment by cwensley** [comment]
No worries @Miepee, I hope you didn't put too much work into it.  I needed it for one of my projects so I thought I'd take a crack at it.

**Pull request closed without merging**
