### PR TITLE
[Gtk] RadioButton shows partial Label when Text is empty #715

### PR DESCRIPTION
**Pull request by jaebird**
This is a partial fix, but need to ensure that RadioButtonHandler.Text is called when the Text of a RadioButton is changed.

### CODE REVIEW

**Comment by jaebird** [comment]
This fixes RadioButton with label Text. Should be ready to go. On a side note: RadioButtonList does not support changing Text once initialized. That does not affect this fix.

**Comment by cwensley** [comment]
Thanks for the PR!  However, it appears there's a problem with the logic..  For example, if you run this code:

```c#
var rb = new RadioButton();

// problem scenario 1:
rb.Text = null; // will try to remove the label

// problem scenario 2:
rb.Text = "Something"; // adds the label, cool
rb.Text = "Something Else"; // will try to add the label again, not so cool
```

Cheers!
Curtis.

**Comment by jaebird** [comment]
Is this blowing up in Gtk3? I tested in Gtk2 and it will not add or remove
a control unless it needs to. That is why I removed the flag logic. If
needed, I can put it back in.

**Comment by cwensley** [comment]
Hm, to be honest I didn't actually test it, though are you sure GTK isn't spewing warning messages when this happens?  Ideally we should minimize those as much as possible.  If there aren't any warning messages, and this is perfectly legal GTK# code, then this should be fine.

**Comment by jaebird** [comment]
I saw no warnings in Gtk2, which is why I removed the extra checks. I
haven't tested in Gtk3 though. I was assuming Gtk was tracking a dictionary
or something. :) I can test more.

**Comment by cwensley** [comment]
Awesome!  Thanks for the PR.

**Pull request merged**
