### PR TITLE
[Gtk] Fix creating icon from fileName

### PR DESCRIPTION
**Pull request by cra0zy**
Notes
1) Faster and less code
2) The original method didn't work, kept throwing "unknown format"

### CODE REVIEW

**Comment by cwensley** [comment]
Thanks for the PR!  Unfortunately, it appears as if it just reverts the update to support Icon.Frames.

What file are you loading?  is it an .ico or a different format of file?  Currently only .ico is supported across all platforms.

**Comment by cra0zy** [comment]
.png

I looked at the examples and you seem to be loading .png images from resources in them, tho loading them from file crashes.

**Comment by cra0zy** [comment]
@cwensley What would you suggest for implementing .png images? I meant where to implement it in Eto?

**Comment by cwensley** [comment]
Right, that feature has only been implemented when loading from resources for now (where it loads @2x, etc files).  I would certainly like to see that supported from file, but hasn't been done yet.

The other platforms most likely will have the same problem as GTK at this point.

I've added issue #483 to track the feature.  If you'd like to try to tackle it let me know, otherwise I will try to get to it soon!

If you want to do this manually, you can compose an icon from many `Bitmap`s by passing an array of `IconFrame` objects to the `Icon` constructor.

Otherwise, use `new Bitmap(fileName)` if you just want to load a single .png directly.

Hope this helps!

**Comment by cra0zy** [comment]
> Otherwise, use new Bitmap(fileName) if you just want to load a single .png directly.

Ok, I wouldn't have guessed that.

> Hope this helps!

As always you are very helpful, Thank You ^^

PS. MonoGame Pipeline Tool is being ported to Eto

**Pull request closed without merging**
