### PR TITLE
Feature/addin update

### PR DESCRIPTION
**Pull request by cwensley**
This is a PR with initial changes to update the VS and XS addins.

- Includes XS 6.x support
- Adds more features to the designer, such as resizing the forms
- Attempts to use Mac platform within Xamarin Studio when running on a Mac, instead of GTK.
- Uses Roslyn compiler for XS addin (may mean dropping VS 2013 support)

### CODE REVIEW

**Comment by tom-corwin** [comment]
Hello!

Do you know when this pull request will be implemented into a MyGet package?

**Comment by cwensley** [comment]
@tom-corwin, this won't be implemented into a MyGet package as the XS and VS addins aren't nuget packages.  You'll have to compile it yourself until the addins are finalized and published to their respective repos.

**Comment by tom-corwin** [comment]
@cwensley Thanks for the reply. I look forward to the next publication for the addin.

**Comment by cwensley** [comment]
@tom-corwin, I've now pushed the new addin to the **alpha** repo on addins.monodevelop.com.  However, if you're using Xamarin Studio 6.1.1 (6.1 or 6.0 is fine), you'll have to manually add this url to the XS addin repository to see it:  http://addins.monodevelop.com/Alpha/6.1/main.mrep

I've poked people about this problem with 6.1.1, so we'll see if they fix it for next version.

**Pull request merged**
