### PR TITLE
Added DropDownToolItem.

### PR DESCRIPTION
**Pull request by allsorts46**
My implementation of DropDownToolItem, to compare/combine with #2243 from @Serg-Norseman. Also added example to the Eto.Test project.

Implemented and tested with Winforms, WPF and GTK. Android implementation also exists but depends on #2277.

### CODE REVIEW

**Comment by allsorts46** [comment]
I encountered an issue in Eto.Test when trying the ToolBarSection on Winforms platform, but it looks like a problem with NumericStepper (or usage thereof) and so I did not commit my workaround on this branch.

I had to modify the SetStepperLimit() method from:

```
void SetStepperLimit()
{
	if (toolBar.Items.Count == 0)
		indexStepper.MinValue = indexStepper.MaxValue = -1;
	else
	{
		indexStepper.MinValue = 0;
		indexStepper.MaxValue = toolBar.Items.Count - 1;
	}
}
```

to:

```
void SetStepperLimit()
{
	if (toolBar.Items.Count == 0)
	{
		indexStepper.MinValue = -1;
		indexStepper.Value = -1;
		indexStepper.MaxValue = -1;
	}
	else
	{
		indexStepper.MaxValue = toolBar.Items.Count - 1;
		indexStepper.MinValue = 0;
	}
}
```

in order to avoid exceptions about invalid values at runtime. Was something about NumericStepper changed recently which broke this code?

**Comment by allsorts46** [comment]
Switched to using ToggleToolButton which allows a 'pressed' look whilst the menu is open. Seems to handle all methods of closing the menu (clicking item, clicking outside, pressing ESC) correctly and looks good with default theme. Unsure if it could look weird with custom GTK themes though.

**Comment by cwensley** [comment]
Awesome, this looks great!  I'll try to add the Mac version and then we can get this merged in.  Thanks for taking the time to submit the PR.

**Comment by Serg-Norseman** [comment]
👍 👍 👍

**Comment by allsorts46** [comment]
Thanks! I also have a LabelToolItem that I wanted to submit in future - basically just non-interactive text in the toolbar. Assuming that's something you'd approve of, I'd need your help for the Mac implementation on that as well. Would it make sense to do both at the same time?

**Comment by Serg-Norseman** [comment]
> Thanks! I also have a LabelToolItem that I wanted to submit in future - basically just non-interactive text in the toolbar. Assuming that's something you'd approve of, I'd need your help for the Mac implementation on that as well. Would it make sense to do both at the same time?

Also a useful item!

**Comment by Serg-Norseman** [comment]
Does the arrow turn off for you only in the Gtk implementation?

**Comment by allsorts46** [comment]
> Does the arrow turn off for you only in the Gtk implementation?

Yes, I only added it on the GTK implementation... but I suppose it should be easy to make the option in a platform-independent way instead as a property on Eto.Forms.DropDownToolItem. For GTK, WPF and Android we are manually _adding_ the arrow anyway so can just choose not to, and the Winforms System.Windows.Forms.ToolStripDropDownButton has a ShowDropDownArrow property. Don't know about Mac.

**Comment by Serg-Norseman** [comment]
In my program in several places such buttons have an arrow, in several they should not have. And it is desirable that the view be the same on all platforms. How can I do this without a shared property in Eto.Forms.DropDownToolItem?

**Comment by allsorts46** [comment]
Winforms and WPF also now allow hiding the drop arrow. I stopped short of added a property on the cross-platform assembly because I don't know if Mac will be able to support it or not. If it turns out it can, we can just add it as a single property in the main Eto assembly instead, which will be much easier to use.

So assuming you have project references to the appropriate platform assemblies, all of these now work:

```
Eto.Style.Add<Eto.GtkSharp.Forms.ToolBar.DropDownToolItemHandler>("NoArrow", h => h.ShowDropArrow = false);
Eto.Style.Add<Eto.WinForms.Forms.ToolBar.DropDownToolItemHandler>("NoArrow", h => h.ShowDropArrow = false);
Eto.Style.Add<Eto.Wpf.Forms.ToolBar.DropDownToolItemHandler>("NoArrow", h => h.ShowDropArrow = false);
```

and then any DropDownToolItem with style 'NoArrow' will not have an arrow on GTK, Winforms or WPF.

**Comment by cwensley** [comment]
Ok so I've worked on this a bit on Mac and I've got this almost ready to go.  ShowDropArrow will also be promoted to a property in DropDownToolItem, which I think makes sense if all platforms support it.

**Comment by cwensley** [comment]
I've now merged a fix that include the DropDownToolItem based this implementation.  Please give it a go and let me know if there's anything amiss.  Thanks @allsorts46 and @Serg-Norseman for doing the legwork to get this implemented!  It will be a very useful feature for Eto.

**Pull request closed without merging**
