### PR TITLE
Gtk Add Combobox and DropDown to Eventbox so mouse events occur

### PR DESCRIPTION
**Pull request by cra0zy**
Fixes: #512

For DropDown no mouse events worked.
For ComboBox only mouse move event worked.

### CODE REVIEW

**Comment by cwensley** [comment]
To give some background, this gives a few benefits:

- Makes the handlers more straightforward, as Control is always the main content of the handler
- The ControlObject property of the Eto control will also return the Gtk.ComboBox, which is the most useful when trying to interact with the native control objects.

**Comment by cra0zy** [comment]
Done.

**Comment by cwensley** [comment]
AWESOME!!  Thanks, right under the line. (;

**Comment by cra0zy** [comment]
Wow that was a fast response...

**Comment by cwensley** [comment]
I'm on a rampage!  (;  That and I'm finishing up the 2.3 release.

**Comment by cra0zy** [comment]
Ah, makes sense.

**Pull request merged**
